name: Build and Run Docker Container

on:
  push:
    branches:
      - main  # Modifier selon votre branche principale

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t mlflow-docker .

      - name: Run Docker container
        run: docker run -d -p 5000:5000 mlflow-docker

      - name: Verify MLflow is running
        run: curl --fail http://localhost:5000/ || exit 1
